name = "demographics"
uuid = "a2343ac2-5142-4a89-9be7-e04b9d0ffe15"
version = "1.0.0-DEV"
authors = ["Avinash Verma <avinash.verma@niser.ac.in> and contributors"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
DataFrames = "1.8.1"
Distributions = "0.25.122"
HTTP = "1.10.19"
JSON = "1.3.0"
SpecialFunctions = "2.6.1"
URIs = "1.6.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
