name = "demographics"
uuid = "a2343ac2-5142-4a89-9be7-e04b9d0ffe15"
version = "1.0.0-DEV"
authors = ["Avinash Verma <avinash.verma@niser.ac.in> and contributors"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
Distributions = "0.25.122"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
